#!/bin/sh

for f in lib/*.jar; do
    CLASSPATH=$CLASSPATH:$f
done
CLASSPATH=$CLASSPATH:src:test:config:data
for f in ~/.clojure/lib/*.jar; do
    CLASSPATH=$CLASSPATH:$f
done
export CLASSPATH
echo CLASSPATH=$CLASSPATH

#check if the first arg is a file, if so use it as a clj-script
if [ -f $1 ] 
then
  java -server -Xmx1G -cp $CLASSPATH jline.ConsoleRunner clojure.main $@
  exit 0;
fi

#no file found launch repl
java -server -Xmx1G -cp $CLASSPATH jline.ConsoleRunner clojure.main -r $@
